name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/Ambev.DeveloperEvaluation.sln

      - name: Build solution
        run: dotnet build ./src/Ambev.DeveloperEvaluation.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ./src/Ambev.DeveloperEvaluation.sln --no-build --configuration Release --verbosity normal
